# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    avatar:
        driver: "%avatar_driver%"
        dimension_default: "%avatar_dimension_default%"
        max_image_size: "%avatar_max_image_size%"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    kernel.event_listener.json_request_transformer:
        class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener
        tags:
              - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

    avatar_service:
        class: AppBundle\Service\AvatarService
        arguments: ["@service_container"]
